version: "3"

services:
  goravel:
    build:
      context: .
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - ./storage:/www/storage
  postgres:
    image: postgres:15.3-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
