CREATE TABLE rekapitulasi.rekap_kejadian_data_keamanan (
  id_rekap_keamanan BIGSERIAL PRIMARY KEY NOT NULL,
  tanggal date NOT NULL,
  type_kejadian_id varchar(45) NOT NULL,
  nama_kapal varchar(45) NOT NULL,
	sumber_berita varchar(45) NOT NULL,
  link_berita varchar(255) NOT NULL,
  lokasi_kejadian varchar(45) NULL,
  muatan varchar(45) NOT NULL,
  asal varchar(45) NULL,
  bendera varchar(45) NULL,
  tujuan varchar(45) NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  kategori_sumber varchar(45) NOT NULL,
  tindak_lanjut varchar(45) NOT NULL,
  imo_kapal varchar(45) NULL,
  mmsi_kapal varchar(45) NULL,
  informasi_kategori varchar(255) NOT NULL,
  zona varchar(45) NOT NULL,
  created_by varchar(45) NOT NULL,
  is_locked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL
);
